#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0


#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0
#
# The client section used by GO SDK.
#
client:
  tls:
    # server是否要验证client证书
    clientAuthRequired: false
    tlsPath: ../config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls
  mspconfig:
    id: Org1MSP
    # [notice] some operation can only be executed by Admin user
    userpath: ../config/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    BCCSP:
      Provider: SW
      Hash: SHA2
      Security: 256
      # Location of Key Store
      FileKeyStore:
        KeyStore:
  # should be "CRITICAL","ERROR","WARNING","NOTICE","INFO","DEBUG"
  logLevel: DEBUG


orderers:
  orderer0.example.com:
    grpcConfig:
      address: grpc://192.168.9.61:8050
      serverNameOverride: orderer0.example.com
      tlsCaCertPath: ../config/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem

  orderer1.example.com:
    grpcConfig:
      address: grpc://192.168.9.61:9050
      serverNameOverride: orderer1.example.com
      tlsCaCertPath: ../config/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem

  orderer2.example.com:
    grpcConfig:
      address: grpc://192.168.9.61:10050
      serverNameOverride: orderer2.example.com
      tlsCaCertPath: ../config/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem


peers:
  peer0.org1.example.com:
    grpcConfig:
      # this Address is used to send endorsement and query requests
      address: grpc://192.168.9.61:7051
      serverNameOverride: peer0.org1.example.com
      tlsCaCertPath: ../config/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    # eventUrl is only needed when using eventhub (default is delivery service)
    eventAddress: grpc://192.168.9.61:7053


timeout:
  event:
    # 同步Invoke事件返回等待时间
    txResponse: 10s
    # 注册事件超时时间
    registrationResponse: 5s