version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yunphant
      POSTGRES_DB: merchant
    ports:
      - 5432:5432
